name = "Interfaces"
uuid = "ef7019ba-fd26-4a4b-83a4-1a87ad57b9d6"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.0.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.4"

[targets]
test = ["Test"]
